# Generated by Django 5.1.2 on 2024-11-08 08:44

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='bg_image',
            field=models.ImageField(upload_to='images/%Y/%m/%d', validators=[blog.models.validate_image_dimensions]),
        ),
    ]
