# Generated by Django 5.1.4 on 2024-12-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_likes_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bg_image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/header_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/post_images'),
        ),
    ]
